### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by owenthewizard** [BrianSidebotham/arm-tutorial-rpi#10]
From the headers of some files it would appear that this project is licensed under the [2-Clause BSD License](https://opensource.org/licenses/BSD-2-Clause). It would be helpful to add a `LICENSE` file.

**Comment by BrianSidebotham** [comment]
Thanks @owenthewizard

Yes, I'll publish it under the 2 clause BSD or MIT license. Whichever is more leanient. I'll sort that out soon while I update the tutorial for RPi3 and RPi3B+

**Comment by BrianSidebotham** [comment]
The MIT License was pushed in a while ago now.
