### ISSUE TITLE
part02 - failed to simulate gdb

### ISSUE THREAD

**Issue by ghost** [BrianSidebotham/arm-tutorial-rpi#11]
in Step02, Simulation: 

after running (gdb) target sim

I get the following output: 
Target byte order unspecified
unable to create simulator instance

how to fix:
(gdb) set endian little
(gdb) target sim

**Comment by BrianSidebotham** [comment]
Thanks for this @modmod24 - I'm about to update the tutorial for RPi3 and RPI3B+. I'll incorporate the changes to Step02 when I get there.

**Comment by BrianSidebotham** [comment]
Unfortunately, none of the toolchains appear appear to be built with the simulator option for some reason nowadays.

**Comment by BrianSidebotham** [comment]
I have removed the references to the simulator now.
