### ISSUE TITLE
part-1/armc-02 missing clflags

### ISSUE THREAD

**Issue by mgcrea** [BrianSidebotham/arm-tutorial-rpi#17]
`part-1/armc-02` won't compile as it is missing the `-DRPIX` cflags in the [build.sh file L46](https://github.com/BrianSidebotham/arm-tutorial-rpi/blob/master/part-1/armc-02/build.sh#L46).

Can do a PR if you want. Thanks for the great tutorial!

**Comment by BrianSidebotham** [comment]
Thanks @mgcrea - I've committed the fix. Sorry - still have a lot of changes in the works to get everything back up to speed. There's been a lot of change recently and adding support for RPI up to 4 has been a pain!
