### ISSUE TITLE
Setting MAXPAGESIZE instead of changing linker script (BMC Part 2 - The C Runtime)

### ISSUE THREAD

**Issue by eyalabraham** [BrianSidebotham/arm-tutorial-rpi#18]
First off, absolutely love this tutorial!

Not sure this is a huge deal, but in [part 2](https://github.com/BrianSidebotham/arm-tutorial-rpi/tree/master/part-2#bmc-part-2---the-c-runtime) you adjust the linked script to get rid of an odd page-alignment behavior. This behavior is governed by the PAGESIZE linker constant that can be controlled by a linked '-z max-page-size=<size>' CLI option, which is also [described here](https://jonathanhamberg.com/post/2018-10-03-decreasing-elf-size/).
I tried this and the page size was reduced accordingly, yielding a smaller image once the .data section is aligned to the new size.
Perhaps a note in the README would be appropriate?

I compile with a '-c' on ```arm-none-eabi-gcc``` and then use the '-z' with ```arm-none-eabi-ld```

**Comment by BrianSidebotham** [comment]
@eyalabraham Looks like great info. Haven't seen that option. I'll introduce it at the end of Part-2. I think we remove the customer linker script at the end of part 2 anyway.

Thanks for the heads up.
