### ISSUE TITLE
Broken / stale web reference 

### ISSUE THREAD

**Issue by rwdavis3rd** [BrianSidebotham/arm-tutorial-rpi#21]
In tutorial BMC Part 2 (The C Runtime) part-2/armc-06, the student is encouraged to look at the ARM instruction set quick reference.  ARM did you a dis-service by removing that PDF at `http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001l/QRC0001_UAL.pdf` but copies of the PDF are still easily-found via Google.   E.g. Cambridge has it at:  `https://www.cl.cam.ac.uk/teaching/2004/ECADArch/datasheets/arm_quick.pdf`

Admittedly, as far as problems go, this is on-par with mouse-nuts.  (I.e. in the global scheme of things, mouse-nuts are quite tiny... but they're still important to the mouse.)   Feel free to dissuade me, if such (well-intended) observations are getting tedious!

**Comment by BrianSidebotham** [comment]
Thanks @rwdavis3rd  I found it on the ARM website still: https://documentation-service.arm.com/static/5ed66080ca06a95ce53f932d so I'll update the documentation.

Your service here is invaluable to me and others. Please keep plugging away. My intention is always for things to be accurate. When you're learning something things need to be water-tight. Learning this stuff is hard enough as it is without bit-rotting documentation and advice!

Hopefully soon I'll get the time to sort out and commit my extensions to the tutorial!
