### ISSUE TITLE
ARMC-09 : gdb simulator gives Unhandled v6 thumb insn: 4601

### ISSUE THREAD

**Issue by BrianSidebotham** [BrianSidebotham/arm-tutorial-rpi#3]
When debugging armc-09 with the arm-none-eabi-gdb simulator the error message

```
Unhandled v6 thumb insn: 4601
```

To repeat:

```
arm-none-eabi-gdb
file kernel.elf
target sim
load
break _start
run
s
....
s
```

is thrown from inside malloc in newlib.

**Comment by cirosantilli** [comment]
I reproduce with a crosstool-ng built with crosstool-ng https://github.com/cirosantilli/newlib-examples/tree/af3116ede68cc7b4192dc5212c556baec3195b25#gdb-builtin-cpu-simulator and then running an userland program compiled with glibc: https://github.com/cirosantilli/arm-assembly-cheat/blob/cd232dcaf32c0ba6399b407e0b143d19b6ec15f4/v7/mov.S (needs to add `-static` as well).

The real question is why not just use GDB as shown at: https://github.com/cirosantilli/newlib-examples/tree/af3116ede68cc7b4192dc5212c556baec3195b25#gdb-builtin-cpu-simulator

**Comment by BrianSidebotham** [comment]
Non of the toolchains these days include the simulator option :(
