### ISSUE TITLE
RPI B+ problems with part-1

### ISSUE THREAD

**Issue by robert-PI** [BrianSidebotham/arm-tutorial-rpi#4]
The bin located  in part-1/armc-03/bin-rpi-bplus/kernel.img is not working on my RPI B+.

I think it is a code problem (maybe is not actualizated with the information given by florin on his coment).

When I change the kernel.img and I put the raspbian img its working so... I think the problem is not in my device or something like that.

thank you

**Comment by BrianSidebotham** [comment]
Oops, this was a broken binary image and build file. Fixing now...

**Comment by robert-PI** [comment]
Thanks Brian.

I am going to continue with your tutorials.

Nice job! congrats!!!!
