### ISSUE TITLE
can't find kernel.img in new ubuntu isos

### ISSUE THREAD

**Issue by amitu** [BrianSidebotham/arm-tutorial-rpi#5]
To use the compiled kernel [CMU tutorial](http://www.cl.cam.ac.uk/projects/raspberrypi/tutorials/os/ok01.html) says:

> To install your operating system, first of all get a Raspberry PI SD card which has an operating system installed already. If you browse the files in the SD card, you should see one called kernel.img. Rename this file to something else, such as kernel_linux.img. Then, copy the file kernel.img that make generated onto the SD Card. You've just replaced the existing operating system with your own. To switch back, simply delete your kernel.img file, and rename the other one back to kernel.img. I find it is always helpful to keep a backup of you original Raspberry Pi operating system, in case you need it again.

I downloaded snappy-ubuntu-core and raspbian, and neither had kernel.img file in it. 

How do you suggest I can proceed? Let me know if I missed something obvious somewhere.

**Comment by BrianSidebotham** [comment]
There's some information included on the website about creating bootable cards. I would have to re-read the tutorials to see if that information is not linked to explicitly. The information is a little outdated (although still valid) and could do with tidying up a bit too. Please see the information on the valvers website: http://www.valvers.com/open-software/raspberry-pi/creating-a-bootable-sd-card/
