### ISSUE TITLE
Adding options -lc -specs=nosys.specs allows arm-none-eabi-gcc v4.9 for compilation

### ISSUE THREAD

**Issue by enthusiasticgeek** [BrianSidebotham/arm-tutorial-rpi#8]
I am wondering if adding options "-lc -specs=nosys.specs" to the build.sh (https://stackoverflow.com/questions/13235748/linker-error-on-a-c-project-using-eclipse) for compiling with arm-none-eabi-gcc v4.9 is considered? It seems to remove all compilation problems with version 4.9 if any.

**Comment by BrianSidebotham** [comment]
Thanks @enthusiasticgeek I will fix this soon as I progress the tutorials so RPi3 and RPi3B+ are covered. Then I'll catapault the gcc version forward to a recent version. Thanks for the specs, I think that may be better than what's there right now.

**Comment by BrianSidebotham** [comment]
We're using gcc 9.x now, and everything appears to be working well.
